// backend/src/seeders/careersSeed.js
//
// 30 Pakistan-localized careers. Salary ranges are PKR / month and reflect
// typical 2024-2025 market rates in Pakistan. Update them yearly.
//
// riasecFit values are 0..10 each, based on O*NET interest profile mappings.
// skillWeights values are 0..10 — how important each skill bucket is for the role.

export const careersSeed = [
  // ─── Technology ─────────────────────────────────────────────
  {
    slug: 'full-stack-developer',
    title: 'Full-Stack Developer',
    summary:
      'Builds both frontend interfaces and backend systems for web applications. High demand in Pakistan\'s growing IT export sector.',
    cluster: 'technology',
    riasecFit: { R: 4, I: 9, A: 6, S: 3, E: 4, C: 6 },
    skillWeights: { technical: 10, analytical: 8, creative: 5, communication: 5, leadership: 3, organization: 6 },
    coreSkills: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'Git', 'REST APIs'],
    educationPaths: ['BSCS / BSIT at UoG, FAST, NUST, COMSATS', 'Saylani Mass IT bootcamp', 'Self-taught + portfolio'],
    salaryPKR: { entry: 80000, mid: 200000, senior: 500000 },
    demand: 'very-high',
    growthOutlook: '+30% over next 5 years (PSEB data trend)',
    workSettings: ['remote', 'office', 'hybrid'],
    relatedCareers: ['frontend-developer', 'backend-developer', 'mobile-app-developer'],
  },
  {
    slug: 'frontend-developer',
    title: 'Frontend Developer',
    summary: 'Specializes in user interfaces, design systems, and browser-based experiences.',
    cluster: 'technology',
    riasecFit: { R: 3, I: 7, A: 8, S: 4, E: 3, C: 5 },
    skillWeights: { technical: 9, analytical: 6, creative: 8, communication: 5, leadership: 2, organization: 5 },
    coreSkills: ['HTML/CSS', 'JavaScript', 'React', 'TypeScript', 'Tailwind', 'Figma'],
    educationPaths: ['BSCS / BSIT', 'DigiSkills.pk Web Development track', 'Bootcamps + portfolio'],
    salaryPKR: { entry: 70000, mid: 170000, senior: 400000 },
    demand: 'very-high',
    growthOutlook: '+25% over 5 years',
    workSettings: ['remote', 'hybrid'],
    relatedCareers: ['ui-ux-designer', 'full-stack-developer'],
  },
  {
    slug: 'backend-developer',
    title: 'Backend Developer',
    summary: 'Designs and builds server-side systems, APIs, and databases that power applications.',
    cluster: 'technology',
    riasecFit: { R: 4, I: 9, A: 3, S: 2, E: 3, C: 7 },
    skillWeights: { technical: 10, analytical: 9, creative: 3, communication: 4, leadership: 3, organization: 7 },
    coreSkills: ['Node.js / Python / Java', 'SQL', 'MongoDB', 'Docker', 'Cloud (AWS/Azure)'],
    educationPaths: ['BSCS / BSSE', 'Coursera Backend specializations'],
    salaryPKR: { entry: 90000, mid: 220000, senior: 550000 },
    demand: 'very-high',
    growthOutlook: '+28% over 5 years',
    workSettings: ['remote', 'office', 'hybrid'],
  },
  {
    slug: 'mobile-app-developer',
    title: 'Mobile App Developer',
    summary: 'Builds native or cross-platform apps for iOS and Android. Strong freelance market in Pakistan.',
    cluster: 'technology',
    riasecFit: { R: 4, I: 8, A: 6, S: 3, E: 4, C: 5 },
    skillWeights: { technical: 10, analytical: 7, creative: 6, communication: 4, leadership: 3, organization: 5 },
    coreSkills: ['React Native / Flutter', 'Swift / Kotlin', 'REST APIs', 'Firebase'],
    educationPaths: ['BSCS', 'YouTube + bootcamps'],
    salaryPKR: { entry: 80000, mid: 200000, senior: 450000 },
    demand: 'high',
    growthOutlook: '+22% over 5 years',
    workSettings: ['remote', 'hybrid'],
  },
  {
    slug: 'data-scientist',
    title: 'Data Scientist',
    summary: 'Extracts insights from data using statistics and machine learning. Emerging field in Pakistani fintech and telecom.',
    cluster: 'technology',
    riasecFit: { R: 3, I: 10, A: 4, S: 3, E: 3, C: 7 },
    skillWeights: { technical: 9, analytical: 10, creative: 5, communication: 6, leadership: 3, organization: 7 },
    coreSkills: ['Python', 'Pandas', 'SQL', 'Statistics', 'ML libraries (scikit-learn)', 'Visualization'],
    educationPaths: ['BSCS / BS Statistics', 'MS Data Science (NUST, FAST)', 'Coursera / Kaggle'],
    salaryPKR: { entry: 100000, mid: 250000, senior: 600000 },
    demand: 'high',
    growthOutlook: '+35% over 5 years',
    workSettings: ['hybrid', 'remote'],
    relatedCareers: ['data-analyst', 'ml-engineer'],
  },
  {
    slug: 'data-analyst',
    title: 'Data Analyst',
    summary: 'Turns raw data into business reports and dashboards. Entry point into the data world.',
    cluster: 'technology',
    riasecFit: { R: 2, I: 9, A: 3, S: 4, E: 4, C: 9 },
    skillWeights: { technical: 7, analytical: 10, creative: 4, communication: 7, leadership: 3, organization: 8 },
    coreSkills: ['Excel', 'SQL', 'Power BI / Tableau', 'Python basics', 'Statistics'],
    educationPaths: ['Bachelors in any quantitative field', 'DigiSkills.pk Data Analytics'],
    salaryPKR: { entry: 60000, mid: 150000, senior: 350000 },
    demand: 'high',
    growthOutlook: '+25% over 5 years',
    workSettings: ['hybrid', 'office'],
  },
  {
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    summary: 'Defends networks and systems against cyber threats. Rapidly growing in Pakistan banking + government.',
    cluster: 'technology',
    riasecFit: { R: 4, I: 9, A: 2, S: 4, E: 4, C: 8 },
    skillWeights: { technical: 9, analytical: 9, creative: 4, communication: 6, leadership: 4, organization: 7 },
    coreSkills: ['Networking', 'Linux', 'SIEM tools', 'Incident response', 'Pen testing basics'],
    educationPaths: ['BSCS / BSCYS', 'CompTIA Security+, CEH'],
    salaryPKR: { entry: 90000, mid: 230000, senior: 550000 },
    demand: 'high',
    growthOutlook: '+30% over 5 years',
    workSettings: ['office', 'hybrid'],
  },
  {
    slug: 'ui-ux-designer',
    title: 'UI/UX Designer',
    summary: 'Designs digital product experiences — research, wireframes, prototypes, visual design.',
    cluster: 'creative',
    riasecFit: { R: 2, I: 6, A: 10, S: 6, E: 4, C: 4 },
    skillWeights: { technical: 5, analytical: 6, creative: 10, communication: 8, leadership: 4, organization: 6 },
    coreSkills: ['Figma', 'User research', 'Prototyping', 'Visual design', 'Design systems'],
    educationPaths: ['BS Design / BSCS + design self-study', 'Google UX Design (Coursera, free audit)'],
    salaryPKR: { entry: 70000, mid: 180000, senior: 400000 },
    demand: 'high',
    growthOutlook: '+20% over 5 years',
    workSettings: ['remote', 'hybrid'],
  },

  // ─── Business / Finance ─────────────────────────────────────
  {
    slug: 'digital-marketing-specialist',
    title: 'Digital Marketing Specialist',
    summary: 'Runs paid ads, SEO, and content campaigns. Booming freelance + agency market in Pakistan.',
    cluster: 'business',
    riasecFit: { R: 2, I: 6, A: 7, S: 6, E: 9, C: 5 },
    skillWeights: { technical: 5, analytical: 7, creative: 8, communication: 9, leadership: 5, organization: 7 },
    coreSkills: ['Google Ads', 'Meta Ads', 'SEO', 'Analytics', 'Copywriting'],
    educationPaths: ['BBA / Mass Comm', 'DigiSkills.pk Digital Marketing track'],
    salaryPKR: { entry: 50000, mid: 130000, senior: 300000 },
    demand: 'very-high',
    growthOutlook: '+25% over 5 years',
    workSettings: ['remote', 'hybrid', 'office'],
  },
  {
    slug: 'content-writer',
    title: 'Content Writer / Copywriter',
    summary: 'Writes articles, web copy, ad copy, and marketing content. Strong global freelance demand from Pakistan.',
    cluster: 'creative',
    riasecFit: { R: 2, I: 7, A: 9, S: 5, E: 5, C: 5 },
    skillWeights: { technical: 4, analytical: 6, creative: 9, communication: 10, leadership: 3, organization: 6 },
    coreSkills: ['Writing craft', 'SEO', 'Research', 'Editing', 'Brand voice'],
    educationPaths: ['BA English / Mass Comm', 'DigiSkills.pk Creative Writing', 'Self-taught + portfolio'],
    salaryPKR: { entry: 40000, mid: 100000, senior: 250000 },
    demand: 'high',
    growthOutlook: '+15% over 5 years',
    workSettings: ['remote'],
  },
  {
    slug: 'financial-analyst',
    title: 'Financial Analyst',
    summary: 'Analyzes investments, budgets, and financial performance for banks and corporates.',
    cluster: 'finance',
    riasecFit: { R: 2, I: 8, A: 2, S: 4, E: 7, C: 9 },
    skillWeights: { technical: 6, analytical: 10, creative: 3, communication: 7, leadership: 5, organization: 9 },
    coreSkills: ['Excel modeling', 'Financial statements', 'Valuation', 'Power BI', 'CFA basics'],
    educationPaths: ['BBA Finance / BS Accounting', 'ACCA / CFA'],
    salaryPKR: { entry: 70000, mid: 180000, senior: 450000 },
    demand: 'high',
    growthOutlook: '+15% over 5 years',
    workSettings: ['office', 'hybrid'],
  },
  {
    slug: 'chartered-accountant',
    title: 'Chartered Accountant (CA / ACCA)',
    summary: 'Handles audit, tax, and financial reporting. Strong respected profession in Pakistan.',
    cluster: 'finance',
    riasecFit: { R: 2, I: 7, A: 1, S: 4, E: 5, C: 10 },
    skillWeights: { technical: 5, analytical: 9, creative: 2, communication: 6, leadership: 5, organization: 10 },
    coreSkills: ['IFRS', 'Audit', 'Tax law', 'ERP systems', 'Excel'],
    educationPaths: ['ICAP CA program', 'ACCA UK', 'BS Accounting + ACCA'],
    salaryPKR: { entry: 80000, mid: 250000, senior: 700000 },
    demand: 'high',
    growthOutlook: 'Steady, +10% over 5 years',
    workSettings: ['office'],
  },
  {
    slug: 'business-analyst',
    title: 'Business Analyst',
    summary: 'Bridges business needs and technical teams. Translates problems into requirements.',
    cluster: 'business',
    riasecFit: { R: 2, I: 8, A: 4, S: 6, E: 7, C: 8 },
    skillWeights: { technical: 5, analytical: 9, creative: 5, communication: 9, leadership: 6, organization: 8 },
    coreSkills: ['Requirements gathering', 'SQL', 'Process mapping', 'Stakeholder management'],
    educationPaths: ['BBA / BSCS', 'CBAP certification'],
    salaryPKR: { entry: 70000, mid: 180000, senior: 400000 },
    demand: 'high',
    growthOutlook: '+18% over 5 years',
    workSettings: ['hybrid', 'office'],
  },
  {
    slug: 'entrepreneur-founder',
    title: 'Entrepreneur / Startup Founder',
    summary: 'Builds and scales own business. Pakistan\'s startup ecosystem (i2i, NIC) is growing.',
    cluster: 'business',
    riasecFit: { R: 4, I: 6, A: 6, S: 6, E: 10, C: 5 },
    skillWeights: { technical: 6, analytical: 8, creative: 8, communication: 9, leadership: 10, organization: 8 },
    coreSkills: ['Product thinking', 'Sales', 'Fundraising', 'Leadership', 'Resilience'],
    educationPaths: ['Any background — what matters is execution', 'NIC incubation programs'],
    salaryPKR: { entry: 0, mid: 200000, senior: 1500000 },
    demand: 'moderate',
    growthOutlook: 'Variable — high-risk high-reward',
    workSettings: ['hybrid', 'remote', 'office'],
  },

  // ─── Engineering ─────────────────────────────────────────────
  {
    slug: 'civil-engineer',
    title: 'Civil Engineer',
    summary: 'Designs and supervises construction of infrastructure. Steady demand with CPEC and housing.',
    cluster: 'engineering',
    riasecFit: { R: 9, I: 8, A: 3, S: 4, E: 5, C: 7 },
    skillWeights: { technical: 9, analytical: 8, creative: 4, communication: 6, leadership: 6, organization: 8 },
    coreSkills: ['AutoCAD', 'Structural design', 'Project management', 'PEC certification'],
    educationPaths: ['BE Civil from PEC-recognized university'],
    salaryPKR: { entry: 70000, mid: 180000, senior: 400000 },
    demand: 'moderate',
    growthOutlook: '+10% with infrastructure projects',
    workSettings: ['field', 'office'],
  },
  {
    slug: 'mechanical-engineer',
    title: 'Mechanical Engineer',
    summary: 'Designs machines, HVAC, and mechanical systems. Manufacturing and energy sectors.',
    cluster: 'engineering',
    riasecFit: { R: 9, I: 8, A: 3, S: 3, E: 4, C: 6 },
    skillWeights: { technical: 9, analytical: 8, creative: 5, communication: 5, leadership: 5, organization: 7 },
    coreSkills: ['SolidWorks', 'Thermodynamics', 'CAD', 'CNC familiarity'],
    educationPaths: ['BE Mechanical from PEC-recognized university'],
    salaryPKR: { entry: 60000, mid: 160000, senior: 380000 },
    demand: 'moderate',
    growthOutlook: '+8% over 5 years',
    workSettings: ['field', 'office'],
  },
  {
    slug: 'electrical-engineer',
    title: 'Electrical Engineer',
    summary: 'Designs power systems, electronics, and increasingly renewable energy installations.',
    cluster: 'engineering',
    riasecFit: { R: 9, I: 9, A: 3, S: 3, E: 4, C: 6 },
    skillWeights: { technical: 9, analytical: 9, creative: 4, communication: 5, leadership: 5, organization: 7 },
    coreSkills: ['Circuit design', 'MATLAB', 'Power systems', 'PLC', 'Embedded basics'],
    educationPaths: ['BE Electrical from PEC-recognized university'],
    salaryPKR: { entry: 70000, mid: 170000, senior: 400000 },
    demand: 'moderate',
    growthOutlook: '+15% (renewables driving growth)',
    workSettings: ['field', 'office'],
  },
  {
    slug: 'renewable-energy-engineer',
    title: 'Renewable Energy Engineer',
    summary: 'Designs solar, wind, and clean energy systems. High-growth field as Pakistan invests in green energy.',
    cluster: 'engineering',
    riasecFit: { R: 8, I: 9, A: 3, S: 5, E: 5, C: 6 },
    skillWeights: { technical: 9, analytical: 9, creative: 5, communication: 6, leadership: 5, organization: 7 },
    coreSkills: ['Solar PV systems', 'PVsyst', 'Energy auditing', 'Grid integration'],
    educationPaths: ['BE Electrical / Energy Engineering', 'Specialization courses'],
    salaryPKR: { entry: 80000, mid: 200000, senior: 450000 },
    demand: 'high',
    growthOutlook: '+30% over 5 years',
    workSettings: ['field', 'office', 'hybrid'],
  },

  // ─── Health ─────────────────────────────────────────────────
  {
    slug: 'medical-doctor',
    title: 'Medical Doctor (MBBS)',
    summary: 'Diagnoses and treats patients. Universally respected, demanding training pathway.',
    cluster: 'health',
    riasecFit: { R: 5, I: 9, A: 3, S: 10, E: 4, C: 7 },
    skillWeights: { technical: 7, analytical: 9, creative: 4, communication: 9, leadership: 6, organization: 8 },
    coreSkills: ['Clinical reasoning', 'Patient communication', 'Anatomy', 'Pharmacology'],
    educationPaths: ['MBBS from PMC-recognized college', 'FCPS / MD specialization'],
    salaryPKR: { entry: 80000, mid: 250000, senior: 800000 },
    demand: 'high',
    growthOutlook: 'Always in demand',
    workSettings: ['hospital', 'clinic'],
  },
  {
    slug: 'pharmacist',
    title: 'Pharmacist',
    summary: 'Dispenses medication, advises on drug therapy, works in hospitals or pharma industry.',
    cluster: 'health',
    riasecFit: { R: 4, I: 9, A: 2, S: 7, E: 4, C: 8 },
    skillWeights: { technical: 7, analytical: 8, creative: 3, communication: 7, leadership: 4, organization: 8 },
    coreSkills: ['Pharmacology', 'Patient counseling', 'Drug interactions', 'Regulatory knowledge'],
    educationPaths: ['Pharm.D from PCP-recognized university'],
    salaryPKR: { entry: 50000, mid: 120000, senior: 280000 },
    demand: 'moderate',
    growthOutlook: '+10% over 5 years',
    workSettings: ['office', 'hospital'],
  },

  // ─── Education / Public Service ──────────────────────────────
  {
    slug: 'school-teacher',
    title: 'School Teacher',
    summary: 'Teaches children at primary or secondary level. Stable government and private sector roles.',
    cluster: 'education',
    riasecFit: { R: 3, I: 6, A: 6, S: 10, E: 5, C: 7 },
    skillWeights: { technical: 4, analytical: 6, creative: 7, communication: 10, leadership: 7, organization: 8 },
    coreSkills: ['Subject mastery', 'Lesson planning', 'Classroom management', 'Patience'],
    educationPaths: ['B.Ed / M.Ed', 'Subject Bachelors + B.Ed'],
    salaryPKR: { entry: 35000, mid: 80000, senior: 180000 },
    demand: 'moderate',
    growthOutlook: 'Stable',
    workSettings: ['office'],
  },
  {
    slug: 'university-lecturer',
    title: 'University Lecturer',
    summary: 'Teaches and conducts research at the university level. Path to academic career.',
    cluster: 'education',
    riasecFit: { R: 2, I: 9, A: 5, S: 8, E: 5, C: 6 },
    skillWeights: { technical: 6, analytical: 9, creative: 6, communication: 9, leadership: 6, organization: 7 },
    coreSkills: ['Research', 'Teaching', 'Publications', 'Curriculum design'],
    educationPaths: ['MS + PhD in field', 'HEC scholar programs'],
    salaryPKR: { entry: 80000, mid: 180000, senior: 400000 },
    demand: 'moderate',
    growthOutlook: 'Steady',
    workSettings: ['office'],
  },
  {
    slug: 'civil-services-officer',
    title: 'Civil Services (CSS) Officer',
    summary: 'Serves in federal government roles after passing CSS examination. Highly competitive, prestigious.',
    cluster: 'public-service',
    riasecFit: { R: 3, I: 7, A: 3, S: 8, E: 8, C: 9 },
    skillWeights: { technical: 4, analytical: 8, creative: 5, communication: 9, leadership: 9, organization: 9 },
    coreSkills: ['Public administration', 'Policy analysis', 'Writing', 'General knowledge'],
    educationPaths: ['Any Bachelors degree + intensive CSS prep'],
    salaryPKR: { entry: 100000, mid: 200000, senior: 500000 },
    demand: 'moderate',
    growthOutlook: 'Stable, prestigious career path',
    workSettings: ['office', 'field'],
  },
  {
    slug: 'lawyer',
    title: 'Lawyer / Advocate',
    summary: 'Represents clients in legal matters, advises on law. Strong demand in corporate and litigation.',
    cluster: 'public-service',
    riasecFit: { R: 2, I: 8, A: 5, S: 6, E: 9, C: 8 },
    skillWeights: { technical: 4, analytical: 9, creative: 6, communication: 10, leadership: 7, organization: 9 },
    coreSkills: ['Legal research', 'Argumentation', 'Drafting', 'Negotiation'],
    educationPaths: ['LLB', 'LLM for specialization', 'Bar Council license'],
    salaryPKR: { entry: 50000, mid: 200000, senior: 800000 },
    demand: 'moderate',
    growthOutlook: '+10% over 5 years',
    workSettings: ['office', 'court'],
  },

  // ─── Creative / Media ────────────────────────────────────────
  {
    slug: 'graphic-designer',
    title: 'Graphic Designer',
    summary: 'Creates visual content for print and digital. Booming freelance market via Fiverr/Upwork.',
    cluster: 'creative',
    riasecFit: { R: 3, I: 5, A: 10, S: 5, E: 4, C: 4 },
    skillWeights: { technical: 5, analytical: 5, creative: 10, communication: 7, leadership: 3, organization: 6 },
    coreSkills: ['Adobe Suite', 'Typography', 'Branding', 'Layout', 'Visual hierarchy'],
    educationPaths: ['BS Design / Fine Arts', 'DigiSkills.pk Graphic Design'],
    salaryPKR: { entry: 40000, mid: 110000, senior: 280000 },
    demand: 'high',
    growthOutlook: '+15% over 5 years',
    workSettings: ['remote', 'hybrid'],
  },
  {
    slug: 'video-editor',
    title: 'Video Editor / Motion Designer',
    summary: 'Edits video content for YouTube, ads, and films. Massive growth with creator economy.',
    cluster: 'creative',
    riasecFit: { R: 4, I: 6, A: 9, S: 4, E: 5, C: 5 },
    skillWeights: { technical: 7, analytical: 5, creative: 10, communication: 6, leadership: 3, organization: 7 },
    coreSkills: ['Premiere Pro', 'After Effects', 'Color grading', 'Storytelling'],
    educationPaths: ['Self-taught via YouTube', 'Mass Comm degree', 'Saylani / DigiSkills courses'],
    salaryPKR: { entry: 50000, mid: 130000, senior: 350000 },
    demand: 'very-high',
    growthOutlook: '+30% over 5 years',
    workSettings: ['remote', 'hybrid'],
  },
  {
    slug: 'journalist',
    title: 'Journalist',
    summary: 'Reports news for print, digital, or broadcast media. Critical role in democratic society.',
    cluster: 'media',
    riasecFit: { R: 3, I: 8, A: 8, S: 7, E: 6, C: 5 },
    skillWeights: { technical: 4, analytical: 8, creative: 8, communication: 10, leadership: 5, organization: 7 },
    coreSkills: ['Investigative research', 'Writing', 'Interviewing', 'Ethics', 'Multimedia'],
    educationPaths: ['BS Mass Communication', 'BA Journalism'],
    salaryPKR: { entry: 40000, mid: 100000, senior: 250000 },
    demand: 'moderate',
    growthOutlook: 'Shifting toward digital',
    workSettings: ['field', 'hybrid'],
  },

  // ─── Science ────────────────────────────────────────────────
  {
    slug: 'research-scientist',
    title: 'Research Scientist',
    summary: 'Conducts academic or industry research. Path through MS/PhD in chosen field.',
    cluster: 'science',
    riasecFit: { R: 5, I: 10, A: 4, S: 4, E: 3, C: 7 },
    skillWeights: { technical: 8, analytical: 10, creative: 6, communication: 7, leadership: 4, organization: 8 },
    coreSkills: ['Research methodology', 'Statistics', 'Lab techniques', 'Writing papers'],
    educationPaths: ['BS + MS + PhD', 'HEC scholarships'],
    salaryPKR: { entry: 80000, mid: 180000, senior: 450000 },
    demand: 'moderate',
    growthOutlook: 'Steady',
    workSettings: ['office', 'lab'],
  },

  // ─── Specialty / Modern ─────────────────────────────────────
  {
    slug: 'product-manager',
    title: 'Product Manager',
    summary: 'Owns product strategy and roadmap. Growing role in Pakistani tech companies.',
    cluster: 'technology',
    riasecFit: { R: 2, I: 8, A: 6, S: 7, E: 9, C: 7 },
    skillWeights: { technical: 6, analytical: 9, creative: 7, communication: 10, leadership: 9, organization: 9 },
    coreSkills: ['User research', 'Roadmapping', 'Stakeholder management', 'Data analysis', 'Vision'],
    educationPaths: ['BSCS / BBA', 'Transition from dev/design/business roles'],
    salaryPKR: { entry: 100000, mid: 280000, senior: 700000 },
    demand: 'high',
    growthOutlook: '+25% over 5 years',
    workSettings: ['hybrid', 'remote'],
  },
  {
    slug: 'devops-engineer',
    title: 'DevOps / Cloud Engineer',
    summary: 'Automates infrastructure and deployment. High-paying specialty in tech.',
    cluster: 'technology',
    riasecFit: { R: 6, I: 9, A: 3, S: 3, E: 4, C: 8 },
    skillWeights: { technical: 10, analytical: 8, creative: 4, communication: 5, leadership: 4, organization: 8 },
    coreSkills: ['Linux', 'Docker', 'Kubernetes', 'AWS/Azure', 'CI/CD', 'Terraform'],
    educationPaths: ['BSCS', 'AWS / Azure certifications'],
    salaryPKR: { entry: 100000, mid: 250000, senior: 600000 },
    demand: 'very-high',
    growthOutlook: '+35% over 5 years',
    workSettings: ['remote', 'hybrid'],
  },
];